services:
  ics-proxy:
    build: .
    restart: unless-stopped
    environment:
      ICS_INPUT_URL: ${ICS_INPUT_URL}
      SERVER_PATH: ${SERVER_PATH}
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      EVENT_PREFIX: ${EVENT_PREFIX:"C:"}
    ports:
      - "${PUBLIC_PORT:-8080}:8080"
